/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.numaproj.pulsar.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DataRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8694814375030929223L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DataRecord\",\"namespace\":\"io.numaproj.pulsar.model\",\"fields\":[{\"name\":\"padding\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"value\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DataRecord> ENCODER =
      new BinaryMessageEncoder<DataRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DataRecord> DECODER =
      new BinaryMessageDecoder<DataRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DataRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DataRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DataRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DataRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DataRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DataRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DataRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DataRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String padding;
   private long value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DataRecord() {}

  /**
   * All-args constructor.
   * @param padding The new value for padding
   * @param value The new value for value
   */
  public DataRecord(java.lang.String padding, java.lang.Long value) {
    this.padding = padding;
    this.value = value;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return padding;
    case 1: return value;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: padding = value$ != null ? value$.toString() : null; break;
    case 1: value = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'padding' field.
   * @return The value of the 'padding' field.
   */
  public java.lang.String getPadding() {
    return padding;
  }


  /**
   * Sets the value of the 'padding' field.
   * @param value the value to set.
   */
  public void setPadding(java.lang.String value) {
    this.padding = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public long getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(long value) {
    this.value = value;
  }

  /**
   * Creates a new DataRecord RecordBuilder.
   * @return A new DataRecord RecordBuilder
   */
  public static io.numaproj.pulsar.model.DataRecord.Builder newBuilder() {
    return new io.numaproj.pulsar.model.DataRecord.Builder();
  }

  /**
   * Creates a new DataRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DataRecord RecordBuilder
   */
  public static io.numaproj.pulsar.model.DataRecord.Builder newBuilder(io.numaproj.pulsar.model.DataRecord.Builder other) {
    if (other == null) {
      return new io.numaproj.pulsar.model.DataRecord.Builder();
    } else {
      return new io.numaproj.pulsar.model.DataRecord.Builder(other);
    }
  }

  /**
   * Creates a new DataRecord RecordBuilder by copying an existing DataRecord instance.
   * @param other The existing instance to copy.
   * @return A new DataRecord RecordBuilder
   */
  public static io.numaproj.pulsar.model.DataRecord.Builder newBuilder(io.numaproj.pulsar.model.DataRecord other) {
    if (other == null) {
      return new io.numaproj.pulsar.model.DataRecord.Builder();
    } else {
      return new io.numaproj.pulsar.model.DataRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for DataRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DataRecord>
    implements org.apache.avro.data.RecordBuilder<DataRecord> {

    private java.lang.String padding;
    private long value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.numaproj.pulsar.model.DataRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.padding)) {
        this.padding = data().deepCopy(fields()[0].schema(), other.padding);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing DataRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(io.numaproj.pulsar.model.DataRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.padding)) {
        this.padding = data().deepCopy(fields()[0].schema(), other.padding);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'padding' field.
      * @return The value.
      */
    public java.lang.String getPadding() {
      return padding;
    }


    /**
      * Sets the value of the 'padding' field.
      * @param value The value of 'padding'.
      * @return This builder.
      */
    public io.numaproj.pulsar.model.DataRecord.Builder setPadding(java.lang.String value) {
      validate(fields()[0], value);
      this.padding = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'padding' field has been set.
      * @return True if the 'padding' field has been set, false otherwise.
      */
    public boolean hasPadding() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'padding' field.
      * @return This builder.
      */
    public io.numaproj.pulsar.model.DataRecord.Builder clearPadding() {
      padding = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public long getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public io.numaproj.pulsar.model.DataRecord.Builder setValue(long value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public io.numaproj.pulsar.model.DataRecord.Builder clearValue() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DataRecord build() {
      try {
        DataRecord record = new DataRecord();
        record.padding = fieldSetFlags()[0] ? this.padding : (java.lang.String) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DataRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<DataRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DataRecord>
    READER$ = (org.apache.avro.io.DatumReader<DataRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.padding == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.padding);
    }

    out.writeLong(this.value);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.padding = null;
      } else {
        this.padding = in.readString();
      }

      this.value = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.padding = null;
          } else {
            this.padding = in.readString();
          }
          break;

        case 1:
          this.value = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










