apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      source:
        generator:
          rpu: 1
          duration: 1s
          msgSize: 10
    - name: p1
      udf:
        builtin:
          name: cat
    - name: out
      sink:
        udsink:
          container:
            image: my-sink:v0.0.3
            imagePullPolicy: Never
            env:
              - name: PULSAR_SERVICE_URL
                valueFrom:
                  configMapKeyRef:
                    name: pulsar-config
                    key: service-url
              - name: PULSAR_TOPIC_NAME
                valueFrom:
                  configMapKeyRef:
                    name: pulsar-config
                    key: topic-name

  edges:
    - from: in
      to: p1
    - from: p1
      to: out