apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      source:
        generator:
          rpu: 1
          duration: 1s
          msgSize: 10
    - name: p1
      udf:
        builtin:
          name: cat
    - name: out
      volumes: #shared between containers that are aprt of the same pod, useful for sharing configurations
        - name: pulsar-config-volume
          configMap:
            name: pulsar-producer-config #creating volume based on pulsar-produver-config 
            items:
              - key: application.yml
                path: application.yml
      sink:
        udsink:
          container:
            image: my-sink:v0.0.3
            args: [ "--spring.config.location=file:/conf/application.yml" ] # use external configuration file as it configuation source 
            imagePullPolicy: Never
            volumeMounts:
              - name: pulsar-config-volume
                mountPath: /conf
  edges:
    - from: in
      to: p1
    - from: p1
      to: out