apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: udsink-pipeline
spec:
  vertices:
    - name: in
      source:
        generator:
          rpu: 1
          duration: 1s
          msgSize: 10
    - name: p1
      udf:
        builtin:
          name: cat
    - name: out
      sink:
        udsink:
          container:
            image: simple-sink-logger:latest  # Updated image tag
            imagePullPolicy: Never

  edges:
    - from: in
      to: p1
    - from: p1
      to: out
