apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
  name: consumer-mvtx
spec:
  # important: keep these replicas, scale, readBatchSize values same as sample
  replicas: 1
  scale:
    min: 1
    max: 1
  limits:
    readBatchSize: 500
  volumes:
    - name: pulsar-config-volume
      configMap:
        name: consumer-config
        items:
          - key: application.yml
            path: application.yml
  source:
    udsource:
      container:
        image: apache-pulsar-java:after-spring-rm
        args: [ "--config=file:/conf/application.yml" ]
        imagePullPolicy: Never
        env:
          # Uncomment to enable debug-level per-message logs
          # - name: LOGGING_LEVEL_IO_NUMAPROJ_PULSAR
          #   value: "DEBUG"
          # Uncomment to switch from JSON to plain-text log output
          # - name: NUMAFLOW_DEBUG
          #   value: "true"
        resources:
          requests:
             # using Numaflow controller default cpu and memory values
            cpu: 100m
            memory: 128Mi
        envFrom:
          - secretRef:
              name: consumer-secret-cloud
        volumeMounts:
          - name: pulsar-config-volume
            mountPath: /conf
  sink:
    log: {}
